#! /bin/sh
############## Autostart ##############
bspc rule -r "*"

xrdb -load  ~/.cache/wal/colors.xresources &

kill $(pgrep picom)
kill $(pgrep polybar)
kill $(pgrep sxhkd)
kill $(pgrep dunst)
kill $(pgrep autocutsel)
kill $(pgrep polkit-agent-helper-1)
kill $(pgrep polkitd)
kill $(pgrep xrandr)


if [ -x /home/kishan/.config/bspwm/xrand.sh ];then
  bash /home/kishan/.config/bspwm/xrand.sh &
fi

sxhkd &
dunst &
numlockx &
picom --config /home/kishan/.config/picom/picom.conf -b &

/usr/libexec/polkit-agent-helper-1  &
/usr/libexec/polkitd  &

autocutsel -s PRIMARY -fork &

if [ -x /usr/bin/polybar ]; then
    bash $HOME/.config/polybar/launch.sh &
fi

feh --bg-fill /home/kishan/Tresorit/backgrounds/wallhaven-e7711w.jpg /home/kishan/Tresorit/backgrounds/wallhaven-28dgqx.png &

xrdb -load  ~/.cache/wal/colors.xresources &
xsetroot -cursor_name left_ptr &
xset r rate 400 44 &
xset mouse 3 6 &

wal -R &
##########################################
bspc monitor Virtual1  -d  art code media
bspc monitor Virtual2  -d  social misc


####### Rules #######

# bspc rule -a "Firefox"            	    desktop="art" focus=on follow=on
# bspc rule -a "mpv"                	    desktop='movie' state=floating center=true border=off follow=on focus=on
# bspc rule -a "Spotify"            	    desktop='art' state=pseudo_tiled border=off follow=on focus=on
bspc rule -a "Lxappearance"       	    state=floating center=true focus=on follow=on
bspc rule -a "Navigator"       state=floating center=true focus=on follow=on
bspc rule -a "Tor Browser"       state=floating center=true focus=on follow=on

bspc rule -a "Org.gnome.Nautilus"             	  state=floating center=true focus=on follow=on border=off
bspc rule -a "File-roller"       	      state=floating center=true follow=on
bspc rule -a "mpv"       	      desktop="media" state=floating center=true focus=on follow=on
bspc rule -a "feh"                	    state=floating follow=on
bspc rule -a "alacritty"                state=pseudo_tiled follow=on
# bspc rule -a "VSCodium"         	  	  desktop='code' focus=on follow=on
# bspc rule -a "Postman"        	  	    desktop='code' focus=on follow=on

######## Global Settings ########
bspc config automatic_scheme        spiral
bspc config pointer_modifier        mod
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

bspc config focus_follows_pointer   true

######## Borders and Gaps ########

bspc config border_radius       50
bspc config border_width         0
bspc config window_gap          15

bspc config bottom_padding       0
bspc config top_padding          0

bspc config split_ratio         0.50
bspc config click_to_focus                true
bspc config history_aware_focus           true

bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config paddingless_monocle   false
bspc config single_monocle        true

# bspc config normal_border_color   \#5e4f77
# bspc config active_border_color   \#9e70a1
# bspc config focused_border_color  \#9e70a1
# bspc config presel_feedback_color \#d15a6e


bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
